# This is a config for E2B sandbox template.
# You can use template ID (v3mvcadufe10t4ed9tm9) or template name (zync-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("zync-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("zync-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('zync-nextjs-test-2')

team_id = "12947f7c-ef5b-4276-8110-27920b404c42"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "zync-nextjs-test-2"
template_id = "v3mvcadufe10t4ed9tm9"
